version: '2'
services:
  nchan:
    restart: always
    image: lloydzhou/nchan
    ports:
      - "8888:80"
    volumes:
      - ./nchan.conf:/etc/nginx/conf.d/default.conf
      - ./htpasswd:/etc/htpasswd



